### ISSUE TITLE
Some tracks do not respond to scrolling

### ISSUE THREAD

**Issue by tonigi** [3dbionotes-community/3DBIONOTES#39]
Occasionally, some right-hand side tracks are immune to zooming and panning. This occurs e.g. with 6H1F, track "Variants", or EMD-11328, "Residue accessibility".

**Comment by jrmacias** [comment]
Thanks a lot for reporting this issue. We'll have a look and try to fix it ASAP.
Regards

**Comment by jrmacias** [comment]
Fixed on myProtVista (46c1ddc).
Some entries annotations lack fields previously considered as "required", so failing without proper exception handling.
